import Head from "next/head";
import Navbar from "@/components/navbar";
import ShoppingCart from "@/components/shoppingCart";
import { Poppins } from "@next/font/google";
import { useAppContext } from "@/components/stateWrapper";

const font = Poppins({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export default function Layout({
  children,
  title,
}: {
  children: React.ReactNode;
  title: string;
}) {
  const { darkMode } = useAppContext();

  return (
    <>
      <Head>
        <title>Next Store {title ? ` | ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${font.className} ${darkMode ? "bg-black" : "bg-white"} `}
      >
        <Navbar />
        <div className="mx-auto flex w-full flex-col items-center">
          {children}
        </div>
        <ShoppingCart />
      </div>
    </>
  );
}
